version: '2'
services:
  db:
    image: postgres:9.5
    hostname: database
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  movieapi:
    image: devdays/movieapi:v0
    hostname: movieapi
    ports:
      - "9095:9095"
    depends_on:
      - db
  actorapi:
    image: devdays/actorapi:v0
    hostname: actorapi
    ports:
      - "8085:8085"
    depends_on:
      - db